#!/bin/bash
set -e && cd "$(dirname $(realpath -s $0))"

chk_py_ver() {
    command -v "$1" >/dev/null 2>&1 && {
        version_check=$("$1" -c 'import sys; print(sys.version_info >= (3, 12))' 2>/dev/null)
        [ "$version_check" = "True" ] && {
            PYTHON=$(command -v "$1")
            echo "Using $1 at \"$PYTHON\""; } } }

[ -z "$PYTHON" ] && chk_py_ver "python"     || :
[ -z "$PYTHON" ] && chk_py_ver "python3"    || :
[ -z "$PYTHON" ] && chk_py_ver "python3.13" || :
[ -z "$PYTHON" ] && chk_py_ver "python3.12" || :
[ -z "$PYTHON" ] && exit 1

chk_py_pip() { "$PYTHON" -c "import pip" 2>/dev/null; }
chk_py_pip || {
    echo "pip is not installed. Running ensurepip."
    "$PYTHON" -m ensurepip; }
chk_py_pip && "$PYTHON" -m pip install --break-system-packages -r requirements.txt \
    || echo "Failed run pip. Please check your Python setup."

DEST=$([ "$(id -u)" -eq 0 ] && echo "/bin/☾" || echo "$HOME/.local/bin/☾")
echo "Installing to \"$DEST\""

(mkdir ./bin || :) >/dev/null 2>&1
echo '#/bin/sh' > ./bin/☾
echo 'exec' \"$PYTHON\" '-u' \""$(realpath refresher.py)"\" '"$@"' >> ./bin/☾
chmod a+x ./bin/☾

(rm "$DEST" || :) >/dev/null 2>&1
ln -s "$(realpath ./bin/☾)" "$DEST"

echo "Preloading cache…"
"$DEST" -c '󷺹⪢1󱅏3⋅ⴵ⭠ᐸ⍟⬓←π⹏ᵜ🃌x≔‹Welcome to ☾! ›⋅3→∘xᑀ+⟞ᴙᐸ⨝𝗻'