/* AUTOGENERATED, DO NOT EDIT */document . body . append(
    (α = mkə(`div` ,  false  , [(mkə(`h4` , {[`𝑆`] : `color:#f00;`} , `This is coolll`)) , (mkə(`button` , {[`onclick`] : (x) => alert("hi") , [`𝑆`] : `color:green;`} , `hehe`)) , (mkə( false  ,  false  , [(`eg${2 + 2}gos`)])) , (mkə(`script` ,  false  , `print(1);`)) , (mkə( false  , {[`𝑆`] : `display:flex;width:300px;height:300px`} , [(mkə("h" + "5" ,  false  , "joe" . repeat(4)))]))]))
) ; 
α . map( (x,...𝔸)=> x . innerText = "joe")